version: '3.2'

services:

  symfony:
    image: symfony:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=prod"
        - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
      dockerfile: ./.docker/Dockerfile
    container_name: symfony5
#    user: 1000:1000
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/code:cached
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "33061:3306"
    volumes:
      - ./var/mysql-data:/var/lib/mysql
      - ./.docker/environments/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"