version: '3.7'

services:

  symfony:
    image: symfony:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
        - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
      dockerfile: .docker/Dockerfile
    container_name: symfony
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/code
    depends_on:
      - mysql
      - rabbitmq
    links:
      - mysql
      - rabbitmq

  supervisord:
    image: symfony:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
        - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
      dockerfile: .docker/Dockerfile
    container_name: supervisord
    user: root
    volumes:
      - ./:/var/www/code
    depends_on:
      - mysql
      - rabbitmq
    links:
      - mysql
      - rabbitmq
    command: ["/usr/bin/supervisord"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "33061:3306"
    volumes:
      - ./var/mysql-data:/var/lib/mysql
      - .docker/environments/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
    volumes:
      - ./var/rabbitmq:/var/lib/rabbitmq